#!/usr/bin/env bash
# Bash script that displays listening ports with the PID and program name.

# Use lsof to get the listening ports with PID and program names
sudo lsof -i -n -P | grep LISTEN | awk '{print $1, $9, $2}'

