#!/usr/bin/env bash
# Bash script that displays listening ports with the PID and program name.

# List listening ports and filter the required information
sudo netstat -tuln | grep LISTEN | awk '{print $1, $4, $7}'

